# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='case_id',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
