# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspect', '0003_auto_20180419_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='status',
            field=models.CharField(blank=True, choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('loss to follow up ', 'Loss to follow up '), ('dead', 'Dead')], max_length=100, null=True),
        ),
    ]
