# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suspect', '0002_suspect_case_id'),
        ('symptom', '0002_auto_20180419_1606'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_status', models.CharField(blank=True, max_length=20, null=True)),
                ('symptoms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='symptom.Symptom')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('Temperature', models.IntegerField(blank=True, null=True)),
                ('lab_sample', models.CharField(blank=True, max_length=20, null=True)),
                ('lab_sample_id', models.CharField(blank=True, max_length=20, null=True)),
                ('next_appointment_date', models.DateField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
                ('suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suspect.Suspect')),
            ],
        ),
    ]
