# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_auto_20180419_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyCheck',
            new_name='DailyFollowUp',
        ),
    ]
