# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20180419_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfollowup',
            name='symptom_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=20, null=True),
        ),
    ]
