# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_auto_20180419_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyfollowup',
            old_name='symptoms',
            new_name='symptom',
        ),
    ]
