# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=14, null=True)),
                ('symptom_notes', models.CharField(blank=True, max_length=14, null=True)),
                ('outbreak', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
