# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='outbreak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outbreak.Outbreak'),
        ),
    ]
